audio_play_sound(sfx_breakmetal, 10, false)
instance_create((x + 16), (y + 16), obj_metaldebris)
instance_create((x + 16), (y + 16), obj_metaldebris)
instance_create((x + 16), (y + 16), obj_metaldebris)
instance_create((x + 16), (y + 16), obj_metaldebris)
